package com.hotel.management.notifications;

public enum NotificationType {
    BOOKING_CONFIRMATION,
    PAYMENT_RECEIVED,
    PAYMENT_PENDING,
    STAFF_TASK_ASSIGNED,
    USER_CREATED,
    INVENTORY_LOW,
    SYSTEM_ALERT,
    REVENUE_REPORT,
    DAILY_SUMMARY,
    COMPLAINT_ESCALATED,
    FACILITY_BOOKING_CONFIRMATION,
    FACILITY_BOOKING_MANAGER_ALERT,
    FACILITY_ISSUE
}

